version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: todo_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    build:
      context: .
    container_name: todo_keycloak
    volumes:
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: todo_keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_IMPORT: opt/jboss/keycloak/imports/realm-export.json
    depends_on:
      - keycloak_db

  mailhog:
    image: mailhog/mailhog
    container_name: todo_mailer
    ports:
      - 8025:8025
      - 1025:1025
    restart: always

volumes:
  keycloak_postgres_data: