version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: todo_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    build:
      context: .
    container_name: todo_keycloak
    volumes:
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    ports:
      - 8443:8443
      - 8080:8080
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: todo_keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME: localhost
    depends_on:
      - keycloak_db

  mailhog:
    image: mailhog/mailhog
    container_name: todo_mailer
    ports:
      - 8025:8025
      - 1025:1025
    restart: always

volumes:
  keycloak_postgres_data: