version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: todo_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    build:
      context: .
    container_name: todo_keycloak
    volumes:
      - ./imports/realm/:/opt/jboss/keycloak/imports
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    expose:
      - 8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: todo_keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_IMPORT: opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`localhost`)
    depends_on:
      - keycloak_db

  traefik:
    image: traefik:v2.3
    container_name: todo_treafik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mailhog:
    image: mailhog/mailhog
    container_name: todo_mailer
    ports:
      - 8025:8025
      - 1025:1025
    labels:
      - traefik.enable=true
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
      - traefik.http.routers.mailhog.rule=Host(`mailhog.localhost`)
    restart: always

volumes:
  keycloak_postgres_data: